### ISSUE TITLE
Offset Errors

### ISSUE THREAD

**Issue by Glitching-Queen** [Mitsukiii/Ledybot#1]
Seems you have not set up the EggBot correctly for USUM or perhaps have wrong OffSet for eggOff.

Where you are defining the Egg start button you put two arguments on "eggbot = new EggBot(pid,Gamename);" which are not defined elsewhere.

So none of this works :P Only the injection and connecting to ultra games. ( P.S i know you are working on GTSBot atm but if everything else you thought was working, isn't then i would go back and correct that)

Have you tested anything you've edited yet? Or going on a whim then fixing after?

**Comment by Mitsukiii** [comment]
looks like i edited the source not correctly, gonna test after lunch the egg bot, should work with the compiled version.

**Comment by Glitching-Queen** [comment]
I tried :P IT doesn't. It works still with SuMo but not USUM it just doesn't change the offsets.

**Comment by Glitching-Queen** [comment]
Yeah it will need more work :/ I tried with your newest edits. it didn't change anything.

**Comment by Mitsukiii** [comment]
looks like the Egg Offset changed on 1.1, gonna adding the new after i found it.
The Offset changes.

**Comment by Glitching-Queen** [comment]
That is a really weird thing to have change between game versions o.o

**Comment by Mitsukiii** [comment]
EggBot fixed for USUM.
